name: jeden_z_dziesieciu
description: A quiz app inspired by '1 z 10'
publish_to: 'none'
version: 1.4.1+8

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2  # (lub najnowsza wersja)
  cupertino_icons: ^1.0.6
  csv: ^6.0.0
  path_provider: ^2.1.1
  audioplayers: ^6.4.0
  shared_preferences: ^2.2.2 
  provider: ^6.1.2
  url_launcher: ^6.2.5
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.16.9

msix_config:
  display_name: "Jeden z 10"
  identity_name: "SzymonMarciniak.Jedenz10"
  publisher: "CN=2B5101A8-1EBF-4B6B-975B-D11F77F68088"
  publisher_display_name: "Szymon Marciniak"
  msix_version: 1.3.5.0
  certificate_path: "c:/users/sajmo/store_cert.pfx"      # or wherever you saved it
  certificate_password: "00000"
  replace_icons: true
  logo_path: assets/msix/logo.png
  store_logo_path: assets/msix/store_logo.png
  high_resolution_icon_path: assets/msix/scale400.png
  splash_screen_image_path: assets/msix/splash.png
  capabilities: runFullTrust, internetClient, picturesLibrary

flutter:
  uses-material-design: true
  assets:
    - assets/pytania_clean.csv
    - assets/default_icon_new.png
    - assets/correct.mp3
    - assets/wrong.mp3
    - assets/start.mp3
    - assets/end.mp3
    - assets/imagine.mp3
