name: jeden_z_dziesieciu
description: A quiz app inspired by '1 z 10'
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4  # (lub najnowsza wersja)
  cupertino_icons: ^1.0.6
  csv: ^5.0.2
  path_provider: ^2.1.1
  audioplayers: ^5.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pytania_clean.csv
    - assets/default_icon_new.png
    - assets/correct.mp3
    - assets/wrong.mp3
