name: jeden_z_dziesieciu
description: A quiz app inspired by '1 z 10'
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2  # (lub najnowsza wersja)
  cupertino_icons: ^1.0.6
  csv: ^6.0.0
  path_provider: ^2.1.1
  audioplayers: ^6.4.0
  shared_preferences: ^2.2.2 
  provider: ^6.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pytania_clean.csv
    - assets/default_icon_new.png
    - assets/correct.mp3
    - assets/wrong.mp3
    - assets/start.mp3
    - assets/end.mp3
