// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtFADSRD0FBjygYOgltD1pUYGR_g2o-JE',
    appId: '1:243060172867:android:d683ebe6a6cc4faea48cf6',
    messagingSenderId: '243060172867',
    projectId: 'jedenz10-566b9',
    storageBucket: 'jedenz10-566b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZOK6VuwNjAYdq2H9jVNKITnstw8katiY',
    appId: '1:243060172867:ios:2ca4298a55a8562fa48cf6',
    messagingSenderId: '243060172867',
    projectId: 'jedenz10-566b9',
    storageBucket: 'jedenz10-566b9.firebasestorage.app',
    iosBundleId: 'com.example.jedenZDziesieciu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsXptSKS2mI_HUeJhBSByogFgfQcBtJH4',
    appId: '1:243060172867:web:90d6a79feda04922a48cf6',
    messagingSenderId: '243060172867',
    projectId: 'jedenz10-566b9',
    authDomain: 'jedenz10-566b9.firebaseapp.com',
    storageBucket: 'jedenz10-566b9.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsXptSKS2mI_HUeJhBSByogFgfQcBtJH4',
    appId: '1:243060172867:web:90d6a79feda04922a48cf6',
    messagingSenderId: '243060172867',
    projectId: 'jedenz10-566b9',
    authDomain: 'jedenz10-566b9.firebaseapp.com',
    storageBucket: 'jedenz10-566b9.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZOK6VuwNjAYdq2H9jVNKITnstw8katiY',
    appId: '1:243060172867:ios:2ca4298a55a8562fa48cf6',
    messagingSenderId: '243060172867',
    projectId: 'jedenz10-566b9',
    storageBucket: 'jedenz10-566b9.firebasestorage.app',
    iosBundleId: 'com.example.jedenZDziesieciu',
  );

}